apiVersion: v1
kind: Service
metadata:
  name: admin-app
  labels:
    app: admin-app
spec:
  selector: 
    app: admin-app
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}